import './globals.css'
import './style/navbar.css'
import './style/footer.css'
import './style/scroll.css'
import './style/header.css'
import './style/service.css'
import './style/hire.css'
import './style/testimonial.css'
import './style/contact.css'

import 'swiper/css'
import 'swiper/css/free-mode'

import Footer from '@/component/Footer/Footer.component'
import Navbar from '@/component/Navbar/Navbar.component'
import ScrollTop from '@/component/ScrollTop/ScrollTop.component'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({
    children,
}: {
    children: React.ReactNode
}): JSX.Element => {
    return (
        <html lang="en">
            {/* <script>

var cursor = document.querySelector(".cursor");
var cursor2 = document.querySelector(".cursor2");

window.addEventListener("mousemove",function(e){
    cursor.style.cssText = cursor2.style.cssText = 
    "left: " + e.clientX + "px; top: " + e.clientY + "px;";
});

</script> */}

            <body className={inter.className}>
                <Navbar />
                {children}
                <Footer />
                <ScrollTop />

                <div className="cursor" />
                <div className="cursor2" />
            </body>
        </html>
    )
}

export default RootLayout
