export const PROJECTS_LIST = [
    {
        name: 'Vision Fire and Security Systems',
        img: '/image/projects/16.jpg',
        url: 'https://visionfiresecuritysystems.com/',
        githubUrl: 'https://github.com/Ashish8689/Vision-security',
        type: 'react',
        stack: ['Next js', 'CSS'],
        latest: true,
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Find N Vibe',
        img: '/image/projects/13.png',
        url: 'https://visionfiresecuritysystems.com/',
        githubUrl: 'https://github.com/open-metadata/OpenMetadata',
        stack: ['React js', 'CSS'],
        type: 'react',
        latest: true,
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'KTR Machinery',
        img: '/image/projects/14.png',
        url: 'https://ktrmachinery.com/',
        type: 'next',
        githubUrl: 'https://github.com/Ashish8689/KTR_nextjs',
        stack: ['Next js', 'CSS'],
        latest: false,
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Food',
        img: '/image/projects/1.jpg',
        url: 'https://ashish-food.netlify.app/',
        type: 'static',
        latest: true,
        githubUrl: 'https://github.com/Ashish8689/food',
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Memory Game',
        img: '/image/projects/15.png',
        url: 'https://darling-pie-08cd06.netlify.app/',
        type: 'react',
        githubUrl: 'https://github.com/Ashish8689/Memory-game',
        latest: false,
        stack: ['React js', 'Typescript', 'CSS'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Organic',
        img: '/image/projects/11.jpg',
        url: 'https://ashish-organic.netlify.app/',
        type: 'react',
        githubUrl: 'https://github.com/Ashish8689/Organic',
        latest: false,
        stack: ['React js', 'CSS'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Fooda',
        img: '/image/projects/3.jpg',
        url: 'https://ashish-fooda.netlify.app/',
        type: 'static',
        githubUrl: 'https://github.com/Ashish8689/food-service',
        latest: false,
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Fitclick',
        img: '/image/projects/9.jpg',
        url: 'https://ashish-fitclick.netlify.app/',
        type: 'static',
        latest: true,
        githubUrl: 'https://github.com/Ashish8689/Fitclick',
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Gym Management',
        img: '/image/projects/10(1).jpg',
        url: 'https://gym-management-24dae.firebaseapp.com/',
        type: 'react',
        githubUrl: 'https://github.com/Ashish8689/gym-management',
        latest: false,
        stack: [
            'React js',
            'CSS',
            'Node js',
            'Express js',
            'MongoDB',
            'Google Auth',
        ],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Flipkart-Clone',
        img: '/image/projects/12.jpg',
        url: 'https://ashish-flipkart-clone.netlify.app/',
        type: 'react',
        latest: false,
        githubUrl: 'https://github.com/Ashish8689/Flipkart-clone',
        stack: ['React js', 'CSS'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Online Payment',
        img: '/image/projects/4.jpg',
        url: 'https://ashish-onlinepayment.netlify.app/',
        type: 'static',
        githubUrl: 'https://github.com/Ashish8689/online-payment',
        stack: ['Html', 'CSS', 'Javascript'],
        latest: false,
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Covid',
        img: '/image/projects/2.jpg',
        url: 'https://covid19-ashish.netlify.app/',
        type: 'static',
        githubUrl: 'https://github.com/Ashish8689/Covid-19',
        latest: false,
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Portfolio',
        img: '/image/projects/8.jpg',
        url: 'https://aashishportfolio.netlify.app/',
        type: 'next',
        githubUrl: 'https://github.com/Ashish8689/ashish-portfolio-v2',
        latest: false,
        stack: ['Next js', 'Typescript', 'CSS'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Mobile',
        img: '/image/projects/6.jpg',
        url: 'https://ashish8689.github.io/mobile/',
        type: 'static',
        githubUrl: 'https://github.com/Ashish8689/mobile',
        latest: false,
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Star Cricket Academy',
        img: '/image/projects/7.jpg',
        url: 'https://ashish-cricketacademy.netlify.app/',
        type: 'static',
        latest: false,
        githubUrl: 'https://github.com/Ashish8689/Star-cricket-academy',
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
    {
        name: 'Armed Defence',
        img: '/image/projects/5.jpg',
        url: 'http://armeddefence.epizy.com/',
        type: 'static',
        latest: false,
        githubUrl: 'https://github.com/Ashish8689/armedDefence',
        stack: ['Html', 'CSS', 'Javascript'],
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi sequi cupiditate at omnis eligendi obcaecati illo similique quibusdam assumenda laboriosam.',
    },
]
